services:
  elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    build:
      context: .
      platforms:
        - linux/amd64
      args:
        - ES_VERSION=8.6.2
    ports:
      - 9200:9200
    environment:
      - cluster.name=lemmagen-test
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - network.host=0.0.0.0
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
